name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Hello, world!"
          echo "The current directory is: $(pwd)"
