name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          CURRENT_USER=$(whoami)
          GITHUB_USERNAME=${GITHUB_ACTOR}
          echo "Current user is: $CURRENT_USER"
          echo "GitHub username is: $GITHUB_USERNAME"
