jobs:
  build:
    steps:
      - name: Check if tests exist
        run: |
          if [ -z "$(npm run-script | grep '^test\b')" ]; then
            echo "No tests found. Skipping test step."
            exit 0
          fi

      - name: Run tests
        run: npm test
